micronaut:
  application:
    name: notifierApi

aws:
  configurations:
    url: ${AWS_URL:`http://localhost:4566`}
#    This variables are used if environments variables are not set
#    region: ${AWS_REGION:`us-east-1`}
#    keyId: ${AWS_KEY_ID:`test`}
#    accessKey: ${AWS_ACCESS_KEY:`test`}
  sns:
    subscription-topic:
      arn: ${SNS_ARN_SUB:`arn:aws:sns:us-east-1:000000000000:subscription-topic`}
    notify-topic:
      arn: ${SNS_ARN_NOTIFY:`arn:aws:sns:us-east-1:000000000000:notify-topic`}
  sqs:
    notification-queue:
      url: ${AWS_QUEUE_URL:`http://localhost:4566/000000000000/send-notification`}

jackson:
  property-naming-strategy: SNAKE_CASE